name: Bump tag

on:
  workflow_dispatch:
  pull_request_target:
    types:
      - closed
  push:
    branches:
      - main

jobs:
  bump-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Display GitHub event payload
        run: |
            jq < "$GITHUB_EVENT_PATH"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get next dev version tag
        id: next-dev-tag
        uses: ./.github/actions/get-next-version
      - name: Display next dev tag on GitHub Actions job panel
        run:
          echo "::notice ::next-dev-tag=${{ steps.next-dev-tag.outputs.next-dev-tag }}"
      - name: Push new tag
        uses: actions/github-script@v5
        if: github.event.pull_request.merged
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: '${{ github.event.pull_request.merge_commit_sha }}',
              ref: 'refs/tags/${{ steps.next-dev-tag.outputs.next-dev-tag }}',
            })
