name: Bump tag

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  bump-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Increment Git tag by 1
        id: increment-tag
        shell: python
        run: |
          import re
          from subprocess import check_output

          def _set_gha_step_output(name, val):
              print(f"::set-output name={name}::{val}")
          tags = check_output(["git", "tag"], text=True).split("\n")
          current_tag = tags[-1]
          _set_gha_step_output("original", current_tag)
          rest, number = re.match(r"(.*?)(\d+)$").groups()
          next_tag = f"{rest}{int(number) + 1}"
          _set_gha_step_output("incremented", next_tag)
      - name: Push new tag
        uses: actions-ecosystem/actions-push-tag@v1
        with:
          tag: ${{ steps.increment-tag.outputs.incremented }}
          # message: '${{ steps.increment-tag.outputs.incremented }}: PR ${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'
