name: Bump tag

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request_target:
    types:
      - closed

jobs:
  bump-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Display GitHub event payload
        run: |
            echo "::group::GitHub event payload"
            jq . "$GITHUB_EVENT_PATH"
            echo "::endgroup::
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Increment Git tag by 1
        id: increment-tag
        shell: python
        run: |
          import re
          from subprocess import check_output

          def _set_gha_step_output(name, val):
              print(f"::set-output name={name}::{val}")
          tags = check_output(["git", "tag"], text=True).strip().split("\n")
          current_tag = tags[-1]
          print(tags, current_tag, sep="\n")
          _set_gha_step_output("original", current_tag)
          rest, number = re.match(r"(.*?)(\d+)$", current_tag).groups()
          next_tag = f"{rest}{int(number) + 1}"
          _set_gha_step_output("incremented", next_tag)
      - name: Push new tag
        if: 'false'
        uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ steps.increment-tag.outputs.incremented }}
          # message: '${{ steps.increment-tag.outputs.incremented }}: PR ${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'
